### ISSUE TITLE
Currencies under wallet transactions not descriptive

### ISSUE THREAD

**Issue by mtkgeek** [reaster/cardano_wallet_sdk#5]
Hi there, the wallet transaction class has a _currencies_ property that returns a map containing all the currencies in that transaction. The key of this map is a string which I believe is the asset id and its value is the quantity. How am I supposed to know what asset this actually is(ticker, actual name) using just this asset id provided?

https://pub.dev/documentation/cardano_wallet_sdk/latest/cardano_wallet_sdk/WalletTransaction/currencies.html

**Comment by reaster** [comment]
Yes,  the Asset code is somewhat of a half-baked implementation, but there is an implementation. Here is how it works: Every wallet has two tables:  
```
  /// balances of native tokens indexed by assetId
  Map<AssetId, Coin> get currencies;

 /// assets present in this wallet indexed by assetId
  Map<AssetId, CurrencyAsset> get assets;  
``` 
Whenever a unique native asset is encountered, its CurrencyAsset will be loaded and stored in the assets map. In theory, everything you need to know about a native asset, including its name, ticker, policyId and even the number of decimal places to use when converting it to a floating point number, can be found in the CurrencyAsset. However, in practice, many of the fields are optional, so you may have to supply some of your own metadata in order to create a good user experience.  
As far as I'm aware, there is no official CurrencyAsset for ADA, so I just made one up:  
``` 
///
/// Pseudo ADA asset instance allows principal asset to be treated like other native tokens.
/// Blockfrost returns 'lovelace' as the currency unit, whereas all other native tokens are identified by their assetId, a hex string.
/// For consistency, 'lovelace' unit values must be converted to lovelaceHex strings.
///
final lovelacePseudoAsset = CurrencyAsset(
  policyId: '',
  assetName: lovelaceHex,
  quantity: '45000000000', //max
  initialMintTxHash: '',
  metadata: CurrencyAssetMetadata(
    name: 'Cardano',
    description: 'Principal currency of Cardano',
    ticker: 'ADA',
    url: 'https://cardano.org',
    logo: null,
    decimals: 6,
  ),
);
``` 
This is always loaded into the assets map under the lovelaceAssetId constant key, so programmatically you can treat ADA like any other asset. If you need to know if its a native asset or not, there are two CurrencyAsset  properties you can use:   
``` 
  bool get isNativeToken => assetId != lovelaceAssetId;
  bool get isADA => assetId == lovelaceAssetId;
```
To be honest, I'm a bit confused as to weather I should just be using 'lovelace' instead of the hex encoded version (used for both lovelaceHex and lovelaceAssetId constants), but if you use the lovelaceAssetId, your code shouldn't break, if I make a change.

**Comment by mtkgeek** [comment]
I understand what you're saying but we don't have this _assets_ map implemented for _transactions_. The _wallet_ itself has this and thus I can get all the info I need about assets in said wallet but when it comes to transactions we have just this 
/// balances of native tokens indexed by assetId
  `Map<AssetId, Coin> get currencies;`
but I this is needed as well
`Map<AssetId, CurrencyAsset> get assets; `

**Comment by reaster** [comment]
No. The framework automatically loads the CurrencyAsset for each native token found in your transactions. You just have to grab it out of the assets map. However, because many of the properties of the CurrencyAsset data structure are optional, you may not have a lot to work with, but I'm giving you everything the blockchain has to give.

**Comment by cokariinc** [comment]
But there is no asset map. Here is the API reference https://pub.dev/documentation/cardano_wallet_sdk/latest/cardano_wallet_sdk/WalletTransaction-class.html#instance-properties

**Comment by reaster** [comment]
The assets property is in the Wallet class:
https://pub.dev/documentation/cardano_wallet_sdk/latest/cardano_wallet_sdk/ReadOnlyWallet-class.html

**Comment by cokariinc** [comment]
Yes, it is but i don't think it helps me in my case.For example, let's say i sent 100 ADA and 500 WMT Tokens and 1000 WWW Tokens in a transaction. When I pull up that transaction I have no way of knowing what I sent because I only get an asset id and the quantity(currencies map). This is not the case with just assets that are in my wallet because the Wallet class has the assets property so I can get some metadata(ticker, name) but I'm completely in the dark with transactions. Maybe I'll just have to query blockfrost to get info on these assets.

**Comment by reaster** [comment]
I guess I'm having trouble understanding your use-case. Barring a bug, if you send WMT or WWW these native tokens will be in your wallet's assets property. The updateWallet method [loads](https://github.com/reaster/cardano_wallet_sdk/blob/82f2ee5dc6ff15dc1e2e8a44bc698478884d7ca3/lib/src/blockchain/blockfrost/blockfrost_blockchain_adapter.dart#L146) ALL a wallet's addresses, then [loads](https://github.com/reaster/cardano_wallet_sdk/blob/82f2ee5dc6ff15dc1e2e8a44bc698478884d7ca3/lib/src/blockchain/blockfrost/blockfrost_blockchain_adapter.dart#L165) ALL the transactions for those addresses, then [loads](https://github.com/reaster/cardano_wallet_sdk/blob/82f2ee5dc6ff15dc1e2e8a44bc698478884d7ca3/lib/src/blockchain/blockfrost/blockfrost_blockchain_adapter.dart#L187) ALL the asset metadata for assets in those transactions. If you're not seeing WMT or WWW metadata, then there is probably a bug in the SDK. If you're expecting to see an assets property in a Transaction, it's not the correct context for this API, transactions are low-level blockchain data.   
If I'm still not getting the issue, you're welcome to send me a code example or better yet a unit test. And this does raise a good point, in that the blockchain API needs to be more accessible.

**Comment by cokariinc** [comment]
so you're saying If I have a wallet
```
ReadOnlyWallet? currentWallet;
```
and I need to get the assets, in the first transaction I can do this?

```
final assets = currentWallet?.transactions[index].assets;

```
Because I can't, that's the problem
